spring:
  application:
    name: 'Tutorial Ahi'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL:jdbc:mysql://localhost:3306}/${DATABASE_NAME:tutorial}
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:Pass475866}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  devtools:
    restart:
      enabled: true